### ISSUE TITLE
Can't use two cameras

### ISSUE THREAD

**Issue by MiniMinerX** [mosure/bevy_gaussian_splatting#111]
Finished `release` profile [optimized] target(s) in 26.51s
     Running `target\release\mod_moco_app.exe`
2024-07-07T06:48:32.677923Z  INFO bevy_winit::system: Creating new window "App" (0v1)
2024-07-07T06:48:33.510099Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 4080 Laptop GPU", vendor: 4318, device: 10208, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "556.12", backend: Vulkan }
2024-07-07T06:48:34.188173Z ERROR space_editor_ui::meshless_visualizer: Failed to dynamic load assets. Loading defaults from memory
2024-07-07T06:48:34.195802Z  INFO space_bevy_xpbd_plugin: Add bevy_xpbd_3d plugin to editor
BevyXpbdPlugin::build
2024-07-07T06:48:34.229887Z  INFO space_editor_ui: Set start state
2024-07-07T06:48:34.573378Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Home", kernel: "22631", cpu: "13th Gen Intel(R) Core(TM) i9-13900HX", core_count: "24", memory: "31.7 GiB" }
2024-07-07T06:48:34.652806Z  INFO space_editor_ui::game_view: Window scale factor: 1.5 egui scale factor: 1
2024-07-07T06:48:34.707773Z  INFO space_editor_ui::game_view: Window scale factor: 1.5 egui scale factor: 1
2024-07-07T06:48:34.712830Z  INFO space_editor_ui::game_view: Window scale factor: 1.5 egui scale factor: 1
2024-07-07T06:48:35.118646Z  INFO space_editor_ui::game_view: Window scale factor: 1.5 egui scale factor: 1
2024-07-07T06:48:42.246221Z ERROR log: Handling wgpu errors as fatal by default

thread '<unnamed>' panicked at C:\Users\minim\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.4\src\backend\wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 389, Vulkan)>`
    In a set_bind_group command
      note: bind group = `gaussian_view_bind_group`
    Dynamic binding offset index 0 with offset 14720 would overrun the buffer bound to bind group 0 -> binding 0. Buffer size is 7680 bytes, the binding binds bytes 0..608, meaning the maximum the binding can be offset is 7072 bytes     

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace  
Encountered a panic in exclusive system `bevy_render::renderer::render_system`!
thread 'main' panicked at C:\Users\minim\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.13.2\src\pipelined_rendering.rs:49:67:

**Comment by mosure** [comment]
related issue: https://github.com/mosure/bevy_gaussian_splatting/issues/47

**Comment by MiniMinerX** [comment]
Thanks I didn't realize, I'll work on solving the issue
